on:
  push:
    branches:
    - master
  workflow_dispatch:
env:
  GH_TOKEN: ${{ secrets.github_token }}
jobs:
  build:
    name: build
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '20.x'
      - name: Install Dependencies
        run: npm install
      - name: Build windows version
        run: npm run dist:win
      - name: Upload the Windows Build Artifact
        uses: actions/upload-artifact@v3.1.2
        with:
          name: windows
          path: ./dist/*.exe
          retention-days: 90
