on:
  push:
    branches:
    - master
  workflow_dispatch:
jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '20.x'
      - name: Push Dir
  # You may pin to the exact commit or the version.
  # uses: casperdcl/push-dir@e351785b3b8a4e27e0aa9cb9bbc9d32a74de036c
        uses: casperdcl/push-dir@v1.0.2
        with:
    # Commit message
          message: Debug artifacts
      # Branch to push to
          branch: master
    # Git committer name
          name: # optional, default is github-actions[bot]
    # Git committer email
          email: # optional, default is 41898282+github-actions[bot]@users.noreply.github.com
    # Directory to push
          dir: debug-artifacts # optional, default is .
    # Set to "true" to force push
          force: # optional
    # Set to "false" to discard any prior commits on the `branch`
(Note: "false" will override `force` to "true")

    history: # optional, default is true
    # Text to inject into a `CNAME` file
    cname: # optional, default is 
    # Set to "true" to add a `.nojekyll` file
    nojekyll: # optional
      - name: Install Dependencies
        run: npm install
      - name: Build windows version
        run: npm run dist:win
      - name: Upload the Windows Build Artifact
        uses: actions/upload-artifact@v3.1.2
        with:
          name: windows
          path: ./dist/*.exe
          retention-days: 90
           
